### ISSUE TITLE
Sandbox Installation Error

### ISSUE THREAD

**Issue by gzero20** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-cloud#10]
Error running code:

make -C sandbox localstatedir=/var/lib/thingengine

Error Snapshot:

![image](https://user-images.githubusercontent.com/13022982/39769880-055bd38c-5320-11e8-8667-fbacd71474b1.png)

**Comment by GQAdonis** [comment]
Changing the -Werror flag in the makefile compilation settings would eliminate this error and allow a build.  Otherwise, the code would have to be revised to use the return values to those functions...

**Comment by gcampax** [comment]
Right, fixing the code to check for return values is what I suggest.
Those calls should fail only in exceptional cases anyway, it's ok to check and exit with an error message if they fail.

**Comment by gzero20** [comment]
What do I replace the -Werror flag?

**Comment by gcampax** [comment]
Are you familiar with C programming and/or Makefiles?

-Werror is the compiler switch to make every warning into an error.
It is specified in the Makefile inside the sandbox folder.

You can either remove the flag entirely, or add something -Wno-error=unused-result right after -Werror (i.e. "treat all warnings as error, except the one of type unused-result, which should just be a warning").
The type of warning in this case is indicated by the compiler at the end of the error line (it says "[-Werror=unused-result]").

If you wish to fix this error, you just need to handle the error from those system calls.
