### ISSUE TITLE
Problem Installing ThingEngine Platform Cloud

### ISSUE THREAD

**Issue by gzero20** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-cloud#11]
I got stuck with the 'yarn install' part. Hope you can assist.

https://github.com/Stanford-Mobisocial-IoT-Lab/thingengine-platform-cloud

_error /home/ubuntu/Almond/repo/thingengine-platform-cloud/node_modules/cvc4: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/ubuntu/Almond/repo/thingengine-platform-cloud/node_modules/cvc4
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.0.0 | linux | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/ubuntu/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/Almond/repo/thingengine-platform-cloud/node_modules/cvc4/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.node-gyp/7.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/7.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/ubuntu/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/Almond/repo/thingengine-platform-cloud/node_modules/cvc4',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ubuntu/Almond/repo/thingengine-platform-cloud/node_modules/cvc4/build'
  CXX(target) Release/obj.target/cvc4/src/node-cvc4.o
../src/node-cvc4.cpp:12:23: fatal error: cvc4/cvc4.h: No such file or directory
compilation terminated.
cvc4.target.mk:94: recipe for target 'Release/obj.target/cvc4/src/node-cvc4.o' failed
make: *** [Release/obj.target/cvc4/src/node-cvc4.o] Error 1
make: Leaving directory '/home/ubuntu/Almond/repo/thingengine-platform-cloud/node_modules/cvc4/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-1055-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v7.0.0/bin/node" "/home/ubuntu/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/Almond/repo/thingengine-platform-cloud/node_modules/cvc4_

Thanks!

**Comment by gcampax** [comment]
You need to install cvc4 development packages.

On Ubuntu bionic, it's enough to install libcvc4-dev. On Ubuntu trusty or older you'll need to install from source: http://cvc4.cs.stanford.edu/downloads

**Comment by gzero20** [comment]
Thanks Giovanni. I actually did that but to no avail. I’ll do the
installation from scratch again

**Comment by gzero20** [comment]
Solved it already. Thanks!

**Comment by gzero20** [comment]
It's solved already. Thanks!
